Search.setIndex({
  docnames: ["index", "science/coriolis_effect", "science/index"],
  envversion: {
    "sphinx.domains.c": 1,
    "sphinx.domains.changeset": 1,
    "sphinx.domains.citation": 1,
    "sphinx.domains.cpp": 1,
    "sphinx.domains.javascript": 1,
    "sphinx.domains.math": 2,
    "sphinx.domains.python": 1,
    "sphinx.domains.rst": 1,
    "sphinx.domains.std": 1,
    sphinx: 56,
  },
  filenames: ["index.rst", "science/coriolis_effect.rst", "science/index.rst"],
  objects: {},
  objnames: {},
  objtypes: {},
  terms: {
    try: 0,
    while: 1,
    The: 1,
    about: 1,
    across: 0,
    act: 1,
    all: 0,
    alreadi: 0,
    also: 0,
    alwai: 1,
    amplifi: 0,
    angl: 1,
    approach: 0,
    area: 2,
    around: 2,
    attenu: 2,
    base: 0,
    basic: 2,
    becaus: 0,
    belief: 0,
    bound: 0,
    call: 1,
    can: [0, 1],
    capabl: 0,
    citat: 0,
    come: 2,
    complet: 1,
    concept: [0, 2],
    corioli: [0, 2],
    depend: [0, 2],
    detail: 0,
    difficult: 1,
    direct: 1,
    disciplin: 0,
    doctor: 0,
    document: [0, 2],
    doppler: 2,
    due: 1,
    each: 2,
    earth: 1,
    educ: 0,
    effect: [0, 2],
    electromagnet: [0, 2],
    electron: 0,
    engin: 0,
    equat: 1,
    equip: 2,
    everi: 2,
    everyth: 1,
    execut: 0,
    exert: 1,
    exist: [0, 1],
    explan: 1,
    extra: 1,
    fact: [0, 1],
    feedback: 0,
    field: [0, 2],
    forc: 1,
    friction: 1,
    from: 0,
    fundament: 0,
    garfield: 1,
    gener: 0,
    get: 0,
    good: 0,
    graviti: 1,
    guid: 0,
    have: 0,
    help: 0,
    hemispher: 1,
    here: [0, 1],
    hide: 0,
    histor: 0,
    hit: 2,
    hour: 1,
    howev: 1,
    ignor: 1,
    increas: 1,
    index: 0,
    influenc: 1,
    introduct: 1,
    inward: 0,
    issu: 0,
    jack: 0,
    jame: 0,
    just: 1,
    kei: 1,
    kg06: 1,
    knauss: 1,
    know: 0,
    knowledg: 0,
    lack: 0,
    larg: 1,
    larger: 0,
    latitud: 1,
    learn: 0,
    left: 1,
    leverag: 0,
    like: 1,
    littl: [0, 1],
    look: [0, 1],
    lot: 0,
    make: 0,
    mani: [0, 2],
    marin: 2,
    maritim: 0,
    master: 0,
    mathemat: 0,
    mathematician: 0,
    matter: 0,
    maximum: 1,
    mayb: 0,
    mean: 0,
    mechan: [0, 2],
    memoris: 0,
    meteorolog: 1,
    meteorologist: 0,
    modul: 0,
    motion: 1,
    much: 0,
    navig: [0, 2],
    need: 0,
    neg: 1,
    north: 1,
    northern: 1,
    notetak: 0,
    object: [1, 2],
    observ: 1,
    oceanographi: 1,
    opposit: 1,
    other: [0, 1],
    our: [0, 2],
    own: 0,
    page: 0,
    particl: 1,
    physic: 1,
    pick: 1,
    piec: 2,
    pole: 1,
    practic: [1, 2],
    precis: 1,
    press: 1,
    pressur: 1,
    problem: 0,
    project: 0,
    propag: 2,
    proport: 1,
    provid: 0,
    rather: [0, 1, 2],
    realiti: 0,
    refer: [0, 2],
    refract: 2,
    regard: 1,
    rel: 1,
    relationship: 1,
    reli: 0,
    right: 1,
    rotat: 1,
    scienc: 0,
    scientif: 2,
    search: 0,
    self: 0,
    serv: 2,
    ship: 0,
    sign: 1,
    simpli: 0,
    sine: 1,
    sit: 1,
    some: 0,
    south: 1,
    southern: 1,
    speed: 1,
    spread: 2,
    start: 1,
    state: 1,
    stick: 0,
    still: 1,
    studi: [0, 2],
    subject: 0,
    suffici: 0,
    surfac: 0,
    take: [0, 1],
    techniqu: 2,
    text: 0,
    than: [0, 2],
    thank: 0,
    thei: 2,
    them: 0,
    thi: [0, 1, 2],
    think: [0, 1],
    time: [0, 2],
    too: 0,
    tool: 0,
    trade: 0,
    train: 0,
    underpin: 2,
    understand: [0, 1],
    unfortun: 0,
    veloc: 1,
    veri: 0,
    want: 0,
    wave: [0, 2],
    waveland: 1,
    weekend: 0,
    welcom: 0,
    what: 0,
    when: [0, 1, 2],
    where: 1,
    work: 0,
    would: 0,
    wrong: 0,
    you: 0,
    zero: 1,
  },
  titles: ["Seafarer", "Coriolis Effect", "Science"],
  titleterms: {
    corioli: 1,
    effect: 1,
    indic: 0,
    scienc: 2,
    seafar: 0,
    tabl: 0,
  },
})
